// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Fallback for `prisma generate` on Vercel when env is not yet injected in postinstall
    url:
      process.env["DATABASE_URL"] ??
      "postgresql://user:password@localhost:5432/dicha_studio?schema=public",
  },
});
